name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Lightsail via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          command_timeout: 20m
          script: |
            # Navigate to app directory
            cd ~/aquarium || exit 1
            
            # Pull latest code
            git pull origin main
            
            # Create .env file with secrets
            cat > .env << EOF
            MONGO_ROOT_USERNAME=${{ secrets.MONGO_ROOT_USERNAME }}
            MONGO_ROOT_PASSWORD=${{ secrets.MONGO_ROOT_PASSWORD }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
            EOF
            
            # Build and deploy with docker-compose
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml build
            docker-compose -f docker-compose.prod.yml up -d
            
            # Clean up old images
            docker image prune -f
            
            # Show status
            echo "=== Deployment Status ==="
            docker-compose -f docker-compose.prod.yml ps
            
            echo "✅ Deployment complete!"

      - name: Verify deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            sleep 10
            cd ~/aquarium
            docker-compose -f docker-compose.prod.yml ps
            curl -f http://localhost || echo "⚠️ Warning: Health check failed"
